#!/usr/bin/env bash
# Sets up the environment (in linux) and runs the makefile .

# Installing SDL2
sudo apt-get update
sudo apt-get install libsdl2-dev -y

# Installing SDL2 image extension
sudo apt-get install libsdl2-image-dev -y

# Run makefile
make
